version: "3.4"
services:

    app:
        container_name: fysiotest-app
        build: ./web/app
        ports:
            - "80:80"
        volumes:
            - ./www/html/fysiotest.local:/var/www/html/fysiotest.local
        links:
            - db
        env_file: ./web/app/.env

    api:
        container_name: fysiotest-api
        build: ./web/api
        ports:
            - "8081:81"
        volumes:
            - ./www/html/api.local:/var/www/html/api.local
        links:
            - db
        env_file: ./web/api/.env

    db:
        image: mongo:3.6
        ports:
            - "27020:27017"
        volumes:
            - ./data/db/mongo:/data/db
            - ./db/backups:/backups
        container_name: db-fysiotest
        env_file: ./db/.env
